# Generated by Django 5.1.7 on 2025-05-13 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Audience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="New Campaign", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("Sent", "Sent"), ("Scheduled", "Scheduled")],
                        default="Scheduled",
                        max_length=50,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[("email", "Email"), ("social", "Social")],
                        default="email",
                        max_length=50,
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        choices=[("Welcome", "Welcome"), ("Product", "Product")],
                        default="Welcome",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "email_marketing",
                    models.BooleanField(
                        default=True, help_text="Agrees to receive email marketing"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LinkButton",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("web", "Web")], max_length=50)),
                ("url", models.URLField()),
                ("new_tab", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("feedback", models.TextField()),
            ],
        ),
    ]
