# Generated by Django 5.1.7 on 2025-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailtool", "0002_sentemail"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("phone", models.CharField(max_length=10)),
            ],
        ),
    ]
