# Generated by Django 5.1.7 on 2025-05-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailtool", "0004_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("feedback", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
